### ISSUE TITLE
Issues when performing analysis of microbiota composition with phyloseq package in R

### ISSUE THREAD

**Issue by ghost** [mahendra-mariadassou/mahendra-mariadassou.github.io#1]
Hi,
lately, I had some issues when performing microbiota composition comparison with phyloseq package. Indeed, when I use a script to retrieve groups and taxa at the phylum level (text below) from dataframe table using this script : 
**dataPSQ.df <- psmelt (phyloseqres_C.HFFD)**  
**familles <- perform_abundance_per_phylum (dataPSQ.df, c("Control","HFFD"))**
 I had all the time this error message:
"_Error in onegroup[[Families[j]]] <- sample_Fam_sum : 
attempt to select less than one element in OneIndex_"
Usually, it works and I haven't any problem!

any help please,
Thank you

the script for perform_abundance_per_phylum function is:
***********************************************************************************
function(dataframe, groups){
  Families <- levels(dataframe$Phylum)
  samples <- levels(as.factor(dataframe$Sample))
  #dataframe$Phylum <- as.character(dataframe$Phylum)
  #dataframe$Sample <- as.character(dataframe$Sample)
  #dataframe$groups <- as.character(dataframe$groups)
  allgroups <- list()
  for(i in 1:length(groups)){
    print(groups[i])
    onegroup <- list()
    for(j in 1:length(Families)){
      print(Families[j])
      sample_Fam_sum <- c()
      samples_gp <- levels(as.factor(dataframe[dataframe$Group==groups[i],2]))
      for(z in 1:length(samples_gp)){
        sample_Fam_sum <- c(sample_Fam_sum,sum(dataframe[dataframe$Sample==samples_gp[z] & dataframe$Phylum==Families[j] & dataframe$Group==groups[i],3]))
        
      }
      print(sample_Fam_sum)
      onegroup[[Families[j]]] <- sample_Fam_sum
    }
    allgroups[[groups[i]]] <- onegroup
  }
  return(allgroups)
}
************************************************************************************

**Comment by mahendra-mariadassou** [comment]
Hi, 

This is an issue related neither to my personal website (which is the repo you posted to) nor to the package phyloseq extended I maintain...

I'm closing it.
